# Copyright (c) 2020, Anders Lervik.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for gpxplotter.

This file is generated by gpxplotter (``setup_version.py``).
"""
SHORT_VERSION = '0.2.2'
VERSION = '0.2.2'
FULL_VERSION = '0.2.2'
GIT_REVISION = '0e573735a0773f4ed8361a10fdf174fbf0e68370'
GIT_VERSION = '0.2.2'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
