# Copyright (c) 2020, Anders Lervik.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for gpxplotter.

This file is generated by gpxplotter (``setup_version.py``).
"""
SHORT_VERSION = '0.2.7'
VERSION = '0.2.7'
FULL_VERSION = '0.2.7'
GIT_REVISION = '68ec74ad27a79a581f5752b01c0c525866b471df'
GIT_VERSION = '0.2.7'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
