# Copyright (c) 2020, Anders Lervik.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for gpxplotter.

This file is generated by gpxplotter (``setup_version.py``).
"""
SHORT_VERSION = '0.1.1'
VERSION = '0.1.1'
FULL_VERSION = '0.1.1'
GIT_REVISION = '102a44ac6d48e3e9f49c112666c2c794262e0b31'
GIT_VERSION = '0.1.1'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
